#!/usr/bin/env zsh
# Copyright (c) 2016 Dyne.org Foundation
# arm-sdk is written and maintained by Ivan J. <parazyd@dyne.org>
#
# This file is part of arm-sdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

## arm-sdk configuration
## ---------------------

## options for `make` when building kernel
MAKEOPTS="-j$(grep -c 'processor' /proc/cpuinfo)"

## devuan official toolchain
compiler="arm-none-eabi-"
export PATH="$PATH:/sbin"

## custom toolchain (armhf) - https://pub.parazyd.cf/mirror/
#compiler="arm-linux-gnueabihf-"
#export PATH="$R/gcc/gcc-arm-linux-gnueabihf-4.7/bin:$PATH:/sbin"

## custom toolchain (armel) - https://pub.parazyd.cf/mirror/
#compiler="arm-eabi-"
#export PATH="$R/gcc/gcc-arm-eabi-linaro-4.6.2/bin:$PATH:/sbin"

## custom toolchain (arm64) - https://pub.parazyd.cf/mirror/

## static qemu arm binary
qemu_bin="/usr/bin/qemu-arm-static" # Devuan
#qemu_bin="/usr/bin/qemu-arm" # Gentoo
