#!/usr/bin/env zsh
#
# ARM SDK configuration

# add here the info of the toolchain and qemu you are using

# Devuan official toolchain
compiler="arm-none-eabi-"
export PATH="$PATH:/sbin"

# custom toolchain (armhf) - https://pub.parazyd.cf/mirror/
#compiler="arm-linux-gnueabihf-"
#export PATH="$PATH:/sbin:$R/toolchains/gcc-arm-linux-gnueabihf-4.7/bin"

# custom toolchain (armel) - https://pub.parazyd.cf/mirror/gcc-arm-eabi-linaro-4.6.2.txz
compiler="arm-eabi-"
export PATH="$PATH:/sbin/$R/toolchains/gcc-arm-eabi-linaro-4.6.2/bin"

# static qemu arm binary
qemu_bin="/usr/bin/qemu-arm-static" # Devuan
#qemu_bin="/usr/bin/qemu-arm" # Gentoo
