#!/usr/bin/env zsh

# ARM SDK configuration
# safe to leave untouched
#
# add here the info of the toolchain you are using
# custom toolchain
compiler="arm-linux-gnueabihf-"
export PATH="$PATH:/sbin:$R/toolchains/gcc-arm-linux-gnueabihf-4.7/bin"
# devuan default toolchain
#compiler="arm-none-eabi-"
#export PATH="$PATH:/sbin"

qemu_bin="/usr/bin/qemu-arm-static" # Devuan
#qemu_bin="/usr/bin/qemu-arm" # Gentoo
