#!/usr/bin/env zsh
#
# Devuan SDK - build management
#
# Copyright (C) 2015-2016 Dyne.org Foundation
# Copyright (C) 2016      parazyd <parazyd@dyne.org>
#
# Devuan SDK is designed, written and maintained by Denis Roio <jaromil@dyne.org>
#
# This source code is free software; you can redistribute it and/or
# modify it under the terms of the GNU Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This source code is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Please refer
# to the GNU Public License for more details.
#
# You should have received a copy of the GNU Public License along with
# this source code; if not, write to: Free Software Foundation, Inc.,
# 675 Mass Ave, Cambridge, MA 02139, USA.
#

init-arm() {
	fn init-arm $*
	armdev="$1"
	req=(armdev)
	ckreq || {
		error "No ARM device specified"
		return 1
	}

	# Build scripts are mapped to a device name here
	arm_map=(
		"raspi2"                "$R/arm/scripts/raspberry-pi-2.sh"
		"bananapi"              "$R/arm/scripts/bananapi.sh"
		"cubieboard2"           "$R/arm/scripts/cubieboard2.sh"
		"chromeacer"            "$R/arm/scripts/chromebook-acer.sh"
	)

	arm_build_device=${arm_map[$armdev]}

	common="$R/arm/common"
	source ${arm_build_device}
}
